# Generated by Django 3.2.20 on 2023-09-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230918_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crossbow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_weapon', to='home.crossbow'),
        ),
    ]
