# Generated by Django 3.2.20 on 2023-09-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_card_ebank_eshop_supplier'),
        ('users', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='electronic_bank',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_electronic_bank', to='home.Ebank'),
        ),
        migrations.AddField(
            model_name='user',
            name='electronic_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_electronic_shop', to='home.eshop'),
        ),
    ]
